### ISSUE TITLE
Invalid argument to create write stream

### ISSUE THREAD

**Issue by truongminh** [sciolist/fcopy#3]
On Node version 6, the following line  cause error `Options must be  string or object`.
https://github.com/sciolist/fcopy/blob/master/lib/copiers/fallback.js#L7
By changing `opts.mode` to `opts`, the issue seems disappeared.

**Comment by sciolist** [comment]
Hey, thanks! The tests weren't running for the fallback mode, fixed and published a new version (0.10).
